<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Overlay.Domain/Overlay.Domain.csproj" />
    <ProjectReference Include="../Overlay.Telemetry/Overlay.Telemetry.csproj" />
    <ProjectReference Include="../Overlay.Processing/Overlay.Processing.csproj" />
    <ProjectReference Include="../Overlay.Widgets.Relative/Overlay.Widgets.Relative.csproj" />
    <ProjectReference Include="../Overlay.Widgets.Fuel/Overlay.Widgets.Fuel.csproj" />
    <ProjectReference Include="../Overlay.Widgets.Flags/Overlay.Widgets.Flags.csproj" />
  </ItemGroup>
</Project>
